services:
  zigchain-wallet-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zigchain-wallet-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - subscribers_data:/app/data
      - ./fit-sanctum-478115-c1-828f08dbfbde.json:/app/fit-sanctum-478115-c1-828f08dbfbde.json:ro

volumes:
  subscribers_data:
