services:
  zigchain-wallet-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zigchain-wallet-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - subscribers_data:/app/data

volumes:
  subscribers_data:
